// Code generated by sqlc. DO NOT EDIT.
// source: example.sql

package requester

import (
	"context"
)

const getCurrentTime = `-- name: GetCurrentTime :one
SELECT NOW()
`

func (q *Queries) GetCurrentTime(ctx context.Context) (interface{}, error) {
	row := q.db.QueryRowContext(ctx, getCurrentTime)
	var now interface{}
	err := row.Scan(&now)
	return now, err
}
