// Code generated by sqlc. DO NOT EDIT.

package requester

import (
	"context"
	"database/sql"
)

type Querier interface {
	WithTx(tx *sql.Tx) *Queries
	GetCurrentTime(ctx context.Context) (interface{}, error)
}

var _ Querier = (*Queries)(nil)
